<a href="https://colab.research.google.com/github/joshuansu0897/NN_Examples/blob/main/dimensiones_tensores_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Scalar**

In [4]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

**Vector**

In [6]:
x = np.array([42, 3, 4, 5, 6, 7])
print(x.shape)
x.ndim

(6,)


1

**Matriz**

In [7]:
x = np.array([
    [42, 3, 4, 5, 6, 7], 
    [42, 3, 4, 5, 6, 7]
])
print(x.shape)
x.ndim

(2, 6)


2

**Tensor**

In [9]:
x = np.array([
    [
      [42, 3, 4, 5, 6, 7], 
      [42, 3, 4, 5, 6, 7]
    ],
    [
      [42, 3, 4, 5, 6, 7], 
      [42, 3, 4, 5, 6, 7]
    ],
    [
      [42, 3, 4, 5, 6, 7], 
      [42, 3, 4, 5, 6, 7]
    ]
])
print(x.shape)
x.ndim

(3, 2, 6)


3

**Reshape**

In [10]:
x = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9],
])
print(x.shape)
x.ndim

(5, 2)


2

In [11]:
x.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
np.transpose(x)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [15]:
x.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])